# Generated by Django 4.0.6 on 2022-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_jobform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=225)),
                ('JobTitle', models.CharField(max_length=225)),
                ('JobLocation', models.CharField(max_length=225)),
                ('ContactEmail', models.CharField(max_length=225)),
                ('WebsiteUrl', models.URLField(max_length=225)),
                ('CompanyLogo', models.ImageField(upload_to='files/cover')),
                ('JobDescription', models.TextField()),
            ],
        ),
    ]
