# Generated by Django 4.0.6 on 2022-12-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Tags',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
